table 'DATE DIM'
	lineageTag: 3d199c8b-efdc-468e-acd9-2fef1ae157d9

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1752d0b0-9650-4316-85f3-53e82f31f481
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthNum
		dataType: int64
		formatString: 0
		lineageTag: 662add4c-974f-41d9-bc2c-5277e36d0654
		summarizeBy: none
		sourceColumn: MonthNum

		annotation SummarizationSetBy = User

	column Month
		dataType: string
		lineageTag: a03f3f26-eeef-4c4e-aaee-eec43ae1cb4f
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthLong
		dataType: string
		lineageTag: da8a8d81-9489-4a93-bf08-ce2d0228db0a
		summarizeBy: none
		sourceColumn: MonthLong

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 8aa9017f-fb6d-4bc4-b6c1-a8c7abf648d7
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 01764a5e-0aa1-464f-b1f8-152325aed0d6
		summarizeBy: none
		sourceColumn: Year
		sortByColumn: CurYearOffset

		changedProperty = SortByColumn

		annotation SummarizationSetBy = User

	column FiscalMonthNum
		dataType: double
		lineageTag: c38f726c-5e5d-43b4-ab24-c27a5cdfdc50
		summarizeBy: none
		sourceColumn: FiscalMonthNum

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FiscalMonth
		dataType: string
		lineageTag: 59b8f245-b75d-4abb-8b39-fa73840cbc2a
		summarizeBy: none
		sourceColumn: FiscalMonth

		annotation SummarizationSetBy = Automatic

	column FiscalMonthLong
		dataType: string
		lineageTag: edb9993d-7ca8-4d47-8aff-6bff9f495a93
		summarizeBy: none
		sourceColumn: FiscalMonthLong

		annotation SummarizationSetBy = Automatic

	column FiscalQuarter
		dataType: string
		lineageTag: 65a8724e-952a-4d89-bea9-5b422dee9a53
		summarizeBy: none
		sourceColumn: FiscalQuarter

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: string
		lineageTag: ca16b6c8-81e2-46e8-8029-39d9f7f74a3a
		summarizeBy: none
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column CurMonthOffset
		dataType: int64
		formatString: 0
		lineageTag: cf80721d-c29c-4d31-abdb-d8bf3b88d8a6
		summarizeBy: none
		sourceColumn: CurMonthOffset

		annotation SummarizationSetBy = User

	column CurQuarterOffset
		dataType: int64
		formatString: 0
		lineageTag: 0c78adc4-b50c-452b-bca5-399ebc9de8ff
		summarizeBy: none
		sourceColumn: CurQuarterOffset

		annotation SummarizationSetBy = User

	column CurYearOffset
		dataType: int64
		formatString: 0
		lineageTag: c0652a0c-49a3-46d3-a0fb-88bf8afa60aa
		summarizeBy: none
		sourceColumn: CurYearOffset

		annotation SummarizationSetBy = User

	column FutureDate
		dataType: string
		lineageTag: 5b9bd2db-6ade-4ef8-8253-c6f33b08b865
		summarizeBy: none
		sourceColumn: FutureDate

		annotation SummarizationSetBy = Automatic

	column CurFiscalYearOffset
		dataType: string
		lineageTag: 7b0d2da1-0bb7-4b01-bf80-32fe14a7e153
		summarizeBy: none
		sourceColumn: CurFiscalYearOffset

		annotation SummarizationSetBy = Automatic

	column MonthYearNum
		dataType: int64
		formatString: 0
		lineageTag: a13fa4b3-0c4e-4eb2-9335-46834a26f802
		summarizeBy: none
		sourceColumn: MonthYearNum

		annotation SummarizationSetBy = User

	column MonthYear
		dataType: string
		lineageTag: 19ee8d69-aca7-421b-a227-ce07ab7b6b6d
		summarizeBy: none
		sourceColumn: MonthYear
		sortByColumn: MonthYearNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MonthYearLong
		dataType: string
		lineageTag: 98772cca-28a7-43f6-8f3c-6ba4196bfd4b
		summarizeBy: none
		sourceColumn: MonthYearLong

		annotation SummarizationSetBy = Automatic

	column WeekdayNum
		dataType: int64
		formatString: 0
		lineageTag: 818e0786-3e7e-4c5e-81c1-04dbf7297a93
		summarizeBy: none
		sourceColumn: WeekdayNum

		annotation SummarizationSetBy = User

	column Weekday
		dataType: string
		lineageTag: 0b7359ed-e2f9-4a81-9e0a-ae03018cc854
		summarizeBy: none
		sourceColumn: Weekday
		sortByColumn: WeekdayNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column WeekdayWeekend
		dataType: string
		lineageTag: 8d16ad14-d22d-494d-87f6-db190c66ff14
		summarizeBy: none
		sourceColumn: WeekdayWeekend

		annotation SummarizationSetBy = Automatic

	column WeekSequenceNum
		dataType: double
		lineageTag: 6e707e18-8d0a-41a9-8ec5-c5368a49c349
		summarizeBy: none
		sourceColumn: WeekSequenceNum

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WeekDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4a356025-2367-49b8-b07d-22142d4b7b59
		summarizeBy: none
		sourceColumn: WeekDate
		sortByColumn: CurWeekOffset

		changedProperty = FormatString

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Week of Year'
		dataType: int64
		formatString: 0
		lineageTag: 16a22d23-3e19-43dc-99f3-faa0cc64d1cc
		summarizeBy: none
		sourceColumn: Week of Year

		annotation SummarizationSetBy = User

	column CurWeekOffset
		dataType: int64
		formatString: 0
		lineageTag: f5b814a0-be08-4168-81b6-d95d42f8ffb7
		summarizeBy: none
		sourceColumn: CurWeekOffset

		annotation SummarizationSetBy = User

	column 'Day of Year'
		dataType: int64
		formatString: 0
		lineageTag: 593256c7-67de-4745-9e50-5261b18bc0d7
		summarizeBy: none
		sourceColumn: Day of Year

		annotation SummarizationSetBy = User

	column Flag_YTD
		dataType: string
		lineageTag: 789a41d3-b891-4725-9c8a-0d6cd52c76ad
		summarizeBy: none
		sourceColumn: Flag_YTD

		annotation SummarizationSetBy = Automatic

	column Flag_MTD
		dataType: string
		lineageTag: edf08566-e714-4184-8633-d10e3e0db586
		summarizeBy: none
		sourceColumn: Flag_MTD

		annotation SummarizationSetBy = Automatic

	column Flag_QTD
		dataType: string
		lineageTag: 2d3010e7-63ef-4d1c-b266-7c52467f5004
		summarizeBy: none
		sourceColumn: Flag_QTD

		annotation SummarizationSetBy = Automatic

	column CurrentDayOffset
		dataType: int64
		formatString: 0
		lineageTag: 1cf61399-dac9-4239-9175-3857d27d3771
		summarizeBy: none
		sourceColumn: CurrentDayOffset

		annotation SummarizationSetBy = User

	partition 'DATE DIM-d6892572-bfcd-4e28-988e-ee9bfc0546c0' = m
		mode: import
		source = ```
				let
				    /*
				    ****This Calendar was created and provided by Avi Singh****
				    ****This can be freely shared as long as this text comment is retained.****
				    http://www.youtube.com/PowerBIPro
				    www.LearnPowerBI.com by Avi Singh
				    */
				    #"LearnPowerBI.com by Avi Singh" = 1,
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2026, 12, 31) /*was "#date(2017, 1, 1)" Updated on 201802027: hard Coded End of Year caused some formulas to break, switching to dynamic date*/,
				    //Used for 'Offset' Column calculations, you may Hard code CurrentDate for testing e.g. #date(2017,9,1)
				    CurrentDate = DateTime.Date(DateTimeZone.SwitchZone(DateTimeZone.LocalNow(),+8)),
				    // Specify the last month in your Fiscal Year, e.g. if June is the last month of your Fiscal Year, specify 6
				    FiscalYearEndMonth = 6,
				    #"==SET PARAMETERS ABOVE==" = 1,
				    #"==Build Date Column==" = #"==SET PARAMETERS ABOVE==",
				    ListDates = List.Dates(StartDate, Number.From(EndDate - StartDate)+1, #duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(ListDates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns as Date" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    // As far as Power BI is concerned, the 'Date' column is all that is needed  But we will continue and add a few Human-Friendly Columns
				    #"Changed Type to Date" = Table.TransformColumnTypes(#"Renamed Columns as Date",{{"Date", type date}}),
				    #"==Add Calendar Columns==" = #"Changed Type to Date",
				    #"Added Calendar MonthNum" = Table.AddColumn(#"==Add Calendar Columns==", "MonthNum", each Date.Month([Date]), Int64.Type),
				    #"Added Month Name" = Table.AddColumn(#"Added Calendar MonthNum", "Month", each Text.Start(Date.MonthName([Date]),3), type text),
				    #"Added Month Name Long" = Table.AddColumn(#"Added Month Name", "MonthLong", each Date.MonthName([Date]), type text),
				    #"Added Calendar Quarter" = Table.AddColumn(#"Added Month Name Long", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Calendar Year" = Table.AddColumn(#"Added Calendar Quarter", "Year", each Date.Year([Date]), Int64.Type),
				    #"==Add Fiscal Calendar Columns==" = #"Added Calendar Year",
				    #"Added FiscalMonthNum" = Table.AddColumn(#"==Add Fiscal Calendar Columns==", "FiscalMonthNum", each if [MonthNum] > FiscalYearEndMonth
				then [MonthNum] - FiscalYearEndMonth
				else [MonthNum] + (12 - FiscalYearEndMonth), type number),
				    #"Added FiscalMonth Name" = Table.AddColumn(#"Added FiscalMonthNum", "FiscalMonth", each [Month]),
				    #"Added FiscalMonth Name Long" = Table.AddColumn(#"Added FiscalMonth Name", "FiscalMonthLong", each [MonthLong]),
				    #"Added FiscalQuarter" = Table.AddColumn(#"Added FiscalMonth Name Long", "FiscalQuarter", each "FQ" & Text.From(Number.RoundUp([FiscalMonthNum] / 3,0))),
				    #"Added FiscalYear" = Table.AddColumn(#"Added FiscalQuarter", "FiscalYear", each "FY" & 
				Text.End(
				  Text.From(
				    if [MonthNum] > FiscalYearEndMonth
				    then [Year] + 1
				    else [Year]
				  )
				  , 2
				)),
				
				    #"==Add Calendar Date Offset Columns==" = #"Added FiscalYear",
				    // Can be used to for example to show the past 3 months(CurMonthOffset = 0, -1, -2)
				    #"Added CurMonthOffset" = Table.AddColumn(#"==Add Calendar Date Offset Columns==", "CurMonthOffset", each ( Date.Year([Date]) - Date.Year(CurrentDate) ) * 12
				+ Date.Month([Date]) - Date.Month(CurrentDate), Int64.Type),
				    // Can be used to for example to show the past 3 quarters (CurQuarterOffset = 0, -1, -2)
				    #"Added CurQuarterOffset" = Table.AddColumn(#"Added CurMonthOffset", "CurQuarterOffset", each /*Year Difference*/
				       ( Date.Year([Date]) - Date.Year(CurrentDate) )*4
				       /*Quarter Difference*/
				      + Number.RoundUp(Date.Month([Date]) / 3) 
				      - Number.RoundUp(Date.Month(CurrentDate) / 3),
				Int64.Type),
				    // Can be used to for example to show the past 3 years (CurYearOffset = 0, -1, -2)
				    #"Added CurYearOffset" = Table.AddColumn(#"Added CurQuarterOffset", "CurYearOffset", each Date.Year([Date]) - Date.Year(CurrentDate), Int64.Type),
				    // Can be used to for example filter out all future dates
				    #"Added FutureDate Flag" = Table.AddColumn(#"Added CurYearOffset", "FutureDate", each if [Date] > CurrentDate then "Future" else "Past" ),
				    // FiscalYearOffset is the only Offset that is different.
				    // FiscalQuarterOffset = is same as CurQuarterOffset
				    // FiscalMonthOffset = is same as CurMonthOffset
				    #"==Add FiscalYearOffset==" = #"Added FutureDate Flag",
				    #"Filtered Rows to CurrentDate" = Table.SelectRows(#"==Add FiscalYearOffset==", each ([Date] = CurrentDate)),
				    CurrentFiscalYear = #"Filtered Rows to CurrentDate"{0}[FiscalYear],
				    #"Continue...Orig Table" = #"==Add FiscalYearOffset==",
				    #"Added CurFiscalYearOffset" = Table.AddColumn(#"Continue...Orig Table", "CurFiscalYearOffset", each Number.From(Text.Range([FiscalYear],2,2)) - 
				Number.From(Text.Range(CurrentFiscalYear,2,2))
				/*Extract the numerical portion, e.g. FY18 = 18*/),
				    #"==Add General Columns==" = #"Added CurFiscalYearOffset",
				    // Used as 'Sort by Column' for MonthYear columns
				    #"Added MonthYearNum" = Table.AddColumn(#"==Add General Columns==", "MonthYearNum", each [Year]*100 + [MonthNum] /*e.g. Sep-2016 would become 201609*/, Int64.Type),
				    #"Added MonthYear" = Table.AddColumn(#"Added MonthYearNum", "MonthYear", each [Month] & "-" & Text.End(Text.From([Year]),2)),
				    #"Added MonthYearLong" = Table.AddColumn(#"Added MonthYear", "MonthYearLong", each [Month] & "-" & Text.From([Year])),
				    #"Added WeekdayNum" = Table.AddColumn(#"Added MonthYearLong", "WeekdayNum", each Date.DayOfWeek([Date]), Int64.Type),
				    #"Added Weekday Name" = Table.AddColumn(#"Added WeekdayNum", "Weekday", each Text.Start(Date.DayOfWeekName([Date]),3), type text),
				    #"Added WeekdayWeekend" = Table.AddColumn(#"Added Weekday Name", "WeekdayWeekend", each if [WeekdayNum] = 0 or [WeekdayNum] = 6
				then "Weekend"
				else "Weekday"),
				    #"==Improve Ultimate Table" = #"Added WeekdayWeekend",
				    #"----Add WeekSequenceNum----" = #"==Improve Ultimate Table",
				    #"Filtered Rows Sundays Only (Start of Week)" = Table.SelectRows(#"----Add WeekSequenceNum----", each ([WeekdayNum] = 0)),
				    #"Added Index WeekSequenceNum" = Table.AddIndexColumn(#"Filtered Rows Sundays Only (Start of Week)", "WeekSequenceNum", 2, 1),
				    #"Merged Queries Ultimate Table to WeekSequenceNum" = Table.NestedJoin(#"==Improve Ultimate Table",{"Date"},#"Added Index WeekSequenceNum",{"Date"},"Added Index WeekNum",JoinKind.LeftOuter),
				    #"Expanded Added Index WeekNum" = Table.ExpandTableColumn(#"Merged Queries Ultimate Table to WeekSequenceNum", "Added Index WeekNum", {"WeekSequenceNum"}, {"WeekSequenceNum"}),
				    // somehow it ends up being unsorted after Expand Column, should not matter for the end table, but makes it harder to debug and check everything is correct. Thus sorting it.
				    #"ReSorted Rows by Date" = Table.Sort(#"Expanded Added Index WeekNum",{{"Date", Order.Ascending}}),
				    #"Filled Down WeekSequenceNum" = Table.FillDown(#"ReSorted Rows by Date",{"WeekSequenceNum"}),
				    #"Replaced Value WeekSequenceNum null with 1" = Table.ReplaceValue(#"Filled Down WeekSequenceNum",null,1,Replacer.ReplaceValue,{"WeekSequenceNum"}),
				    #"Inserted Start of Week (WeekDate)" = Table.AddColumn(#"Replaced Value WeekSequenceNum null with 1", "WeekDate", each Date.EndOfWeek([Date])),
				    // Added 2019-Oct
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Start of Week (WeekDate)", "Week of Year", each Date.WeekOfYear([Date]), Int64.Type),
				    #"----WeekSequenceNum Complete----" = #"Inserted Week of Year",
				    Current_WeekSequenceNum = #"----WeekSequenceNum Complete----"{[Date = CurrentDate]}?[WeekSequenceNum],
				    #"Added Custom CurWeekOffset" = Table.AddColumn(#"----WeekSequenceNum Complete----", "CurWeekOffset", each [WeekSequenceNum] - Current_WeekSequenceNum, Int64.Type),
				    // Adding a DayofYear 1 to 365
				    // And YTD, QTD, MTD Columns (can help with showing YTD Numbers across multiple years)
				    #"==Updates 2019-Feb DayofYear and YTD QTD MTD Columns" = #"Added Custom CurWeekOffset",
				    // This maybe useful in some DAX Calculations
				    #"Inserted Day of Year" = Table.AddColumn(#"==Updates 2019-Feb DayofYear and YTD QTD MTD Columns", "Day of Year", each Date.DayOfYear([Date]), Int64.Type),
				    #"Added Flag_YTD" = Table.AddColumn(#"Inserted Day of Year", "Flag_YTD", each if Date.DayOfYear([Date]) <= Date.DayOfYear(CurrentDate)
				 then "YTD"
				 else null),
				    #"Added Flag_MTD" = Table.AddColumn(#"Added Flag_YTD", "Flag_MTD", each if Date.Day([Date]) <= Date.Day(CurrentDate)
				 then "MTD"
				 else null),
				    #"Added Flag_QTD" = Table.AddColumn(#"Added Flag_MTD", "Flag_QTD", each //Compare Month Number in Quarter (1,2,3) for [Date] and CurrentDate
				if Number.Mod(Date.Month([Date])-1, 3) + 1
				<= Number.Mod(Date.Month(CurrentDate)-1, 3) + 1
				then "QTD"
				else null),
				    #"==Update 2019-Mar CurrentDatOffset" = #"Added Flag_QTD",
				    #"Added CurrentDayOffset" = Table.AddColumn(#"==Update 2019-Mar CurrentDatOffset", "CurrentDayOffset", each [Date] - CurrentDate),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added CurrentDayOffset",{{"CurrentDayOffset", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each true),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"WeekDate", type date}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

