table 'INVOICE DATE DIM'
	lineageTag: 511db4da-4aa4-421b-97a7-4a86c40b770c

	column 'Invoice Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: d2882b77-627a-44d1-a7f7-e6fb10e39f28
		summarizeBy: none
		sourceColumn: Invoice Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthNum
		dataType: int64
		formatString: 0
		lineageTag: a903589c-7c7a-48e7-8d23-8e4cb8393931
		summarizeBy: none
		sourceColumn: MonthNum

		annotation SummarizationSetBy = User

	column Month
		dataType: string
		lineageTag: 52e96587-4709-4d21-8807-14845fe5cd4f
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthLong
		dataType: string
		lineageTag: 04ec8d58-8b46-416a-ae8c-181e58497115
		summarizeBy: none
		sourceColumn: MonthLong

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 43cd7f43-bf3d-4e22-8d7b-9e0d656210a0
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 3ca34a1a-fe67-4924-bdb1-43bbdb404d7a
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column FiscalMonthNum
		dataType: double
		lineageTag: 86785e17-8af7-4406-a739-3f82d5407690
		summarizeBy: sum
		sourceColumn: FiscalMonthNum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FiscalMonth
		dataType: string
		lineageTag: 8c4093d7-fabe-4bbc-946e-5da5fda6f467
		summarizeBy: none
		sourceColumn: FiscalMonth

		annotation SummarizationSetBy = Automatic

	column FiscalMonthLong
		dataType: string
		lineageTag: b0734926-d197-4dec-a65b-33b67833144e
		summarizeBy: none
		sourceColumn: FiscalMonthLong

		annotation SummarizationSetBy = Automatic

	column FiscalQuarter
		dataType: string
		lineageTag: b2ffc71f-eeb9-41c1-ba3e-b3efe6d7e403
		summarizeBy: none
		sourceColumn: FiscalQuarter

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: string
		lineageTag: 35c79da4-7b9e-428f-a1a1-1d2c38fd162b
		summarizeBy: none
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column CurMonthOffset
		dataType: int64
		formatString: 0
		lineageTag: bc9a9999-5ce9-4286-91ca-d9862796167b
		summarizeBy: sum
		sourceColumn: CurMonthOffset

		annotation SummarizationSetBy = Automatic

	column CurQuarterOffset
		dataType: int64
		formatString: 0
		lineageTag: eba00f7f-2dde-4ee2-8db3-d7f276487925
		summarizeBy: sum
		sourceColumn: CurQuarterOffset

		annotation SummarizationSetBy = Automatic

	column CurYearOffset
		dataType: int64
		formatString: 0
		lineageTag: 08c828eb-3618-4d65-aafc-2c5a7d9d4f3a
		summarizeBy: sum
		sourceColumn: CurYearOffset

		annotation SummarizationSetBy = Automatic

	column FutureDate
		dataType: string
		lineageTag: 409a9c44-e18f-4102-b017-c4a891b4fc3a
		summarizeBy: none
		sourceColumn: FutureDate

		annotation SummarizationSetBy = Automatic

	column CurFiscalYearOffset
		dataType: string
		lineageTag: 704012b4-eca5-4f11-8fa6-1be7f56ba898
		summarizeBy: none
		sourceColumn: CurFiscalYearOffset

		annotation SummarizationSetBy = Automatic

	column MonthYearNum
		dataType: int64
		formatString: 0
		lineageTag: 92f208b0-5c7d-41e0-ad87-07f92b339ceb
		summarizeBy: none
		sourceColumn: MonthYearNum

		annotation SummarizationSetBy = User

	column MonthYear
		dataType: string
		lineageTag: 81ac249d-2b14-4a8c-ac1d-e445e663de7c
		summarizeBy: none
		sourceColumn: MonthYear
		sortByColumn: MonthYearNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MonthYearLong
		dataType: string
		lineageTag: 67859a51-5dfc-42d7-83a5-f534936b1fe2
		summarizeBy: none
		sourceColumn: MonthYearLong

		annotation SummarizationSetBy = Automatic

	column WeekdayNum
		dataType: int64
		formatString: 0
		lineageTag: 1853696e-8969-45ea-b006-e789c416fb86
		summarizeBy: none
		sourceColumn: WeekdayNum

		annotation SummarizationSetBy = User

	column Weekday
		dataType: string
		lineageTag: 90f73b4d-3843-447b-b18e-ee89c68f5af8
		summarizeBy: none
		sourceColumn: Weekday
		sortByColumn: WeekdayNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column WeekdayWeekend
		dataType: string
		lineageTag: cffddd46-e594-4aab-87d2-02f4e22fc5b3
		summarizeBy: none
		sourceColumn: WeekdayWeekend

		annotation SummarizationSetBy = Automatic

	column WeekSequenceNum
		dataType: double
		lineageTag: e2e08561-decc-439f-a6c7-f8329d35d6d8
		summarizeBy: none
		sourceColumn: WeekSequenceNum

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WeekDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 244d7c48-5b91-4d81-9f2e-37adaf15a454
		summarizeBy: none
		sourceColumn: WeekDate

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Week of Year'
		dataType: int64
		formatString: 0
		lineageTag: ecaf0c6b-b411-4423-94a4-53805e9b8a4a
		summarizeBy: none
		sourceColumn: Week of Year

		annotation SummarizationSetBy = User

	column CurWeekOffset
		dataType: int64
		formatString: 0
		lineageTag: ab3a8138-928e-4792-bc78-041b50ca0d09
		summarizeBy: none
		sourceColumn: CurWeekOffset

		annotation SummarizationSetBy = User

	column 'Day of Year'
		dataType: int64
		formatString: 0
		lineageTag: af9233ff-d4e4-423a-a5d1-16d95dcf2c92
		summarizeBy: sum
		sourceColumn: Day of Year

		annotation SummarizationSetBy = Automatic

	column Flag_YTD
		dataType: string
		lineageTag: c4548996-716c-400f-9ac7-5592a0f72972
		summarizeBy: none
		sourceColumn: Flag_YTD

		annotation SummarizationSetBy = Automatic

	column Flag_MTD
		dataType: string
		lineageTag: ea2b2278-4c3c-406e-afb2-b1f5aa221010
		summarizeBy: none
		sourceColumn: Flag_MTD

		annotation SummarizationSetBy = Automatic

	column Flag_QTD
		dataType: string
		lineageTag: 6a60e71f-c454-494c-9d42-20c29d7a595e
		summarizeBy: none
		sourceColumn: Flag_QTD

		annotation SummarizationSetBy = Automatic

	column CurrentDayOffset
		dataType: int64
		formatString: 0
		lineageTag: 5e0cd014-3b91-436f-b289-7171bf5bc365
		summarizeBy: sum
		sourceColumn: CurrentDayOffset

		annotation SummarizationSetBy = Automatic

	partition 'INVOICE DATE DIM-f6590111-a507-4537-8694-54828db7463c' = m
		mode: import
		source =
				let
				    Source = #"DATE DIM",
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Date", "Invoice Date"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

